'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {Agent,validateArgs}=require('../src/agent.cjs');
const {Task}=require('../src/agent-task.cjs');
const response=message=>new Response(JSON.stringify({choices:[{message}]}));
const call=(id,name,args={})=>({id,type:'function',function:{name,arguments:JSON.stringify(args)}});
async function fixture(options){const directory=await fs.mkdtemp(path.join(os.tmpdir(),'arus-task-'));const agent=new Agent({directory,context:async()=>({selected:null}),execute:async()=>({ok:true}),notify:()=>{},...options});await agent.ready;await agent.save({baseUrl:'http://localhost:1234/v1',model:'mock',files:agent.config.files});return {agent,close:()=>fs.rm(directory,{recursive:true,force:true})};}
function validHistory(messages){for(let i=0;i<messages.length;i++){const m=messages[i];if(m.tool_calls){const ids=new Set(m.tool_calls.map(c=>c.id));for(let n=0;n<ids.size;n++)assert.equal(messages[i+1+n].role,'tool');assert.deepEqual(new Set(messages.slice(i+1,i+1+ids.size).map(r=>r.tool_call_id)),ids);}}}
test('round limit keeps original task and complete tool history for Resume',async()=>{
 let step=0,executed=0;const sent=[];const f=await fixture({execute:async()=>({ok:++executed}),fetch:async(_u,o)=>{const data=JSON.parse(o.body);sent.push(data);return ++step<=16?response({tool_calls:[call('step'+step,'filter_traffic',{query:String(step)})]}):response({content:'Lanjutan selesai.'});}});
 try{const paused=await f.agent.chat({text:'Original goal: inspect the session.'});assert(paused.paused);assert.equal(f.agent.state().task.canResume,true);assert.equal(executed,16);const result=await f.agent.resume();assert.equal(result.text,'Lanjutan selesai.');validHistory(sent.at(-1).messages);assert(sent.at(-1).messages.some(m=>m.content==='Original goal: inspect the session.'));assert.equal(f.agent.state().task.status,'completed');assert.equal(f.agent.state().task.canResume,false);}finally{await f.close();}
});
test('handoff stops remaining batch; resume preserves plan and blocks completed mutation replay',async()=>{
 let step=0,replayed=0;const f=await fixture({execute:async name=>{if(name==='replay_request')replayed++;return {done:true};},fetch:async(_u,o)=>{const data=JSON.parse(o.body);validHistory(data.messages);step++;if(step===1)return response({tool_calls:[call('plan','plan_task',{steps:['Send once','Check result']}),call('send','replay_request',{id:'r1'}),call('done','update_task',{stepId:'1',status:'done'}),call('manual','request_handoff',{reason:'Complete manual input.'}),call('skip','clear_traffic')]});if(step===2)return response({tool_calls:[call('duplicate','replay_request',{id:'r1'}),call('finish','update_task',{stepId:'2',status:'done'})]});assert(JSON.parse(data.messages.find(m=>m.tool_call_id==='duplicate').content).blocked);return response({content:'Verified.'});}});
 try{const result=await f.agent.chat({text:'Send once and verify.'});assert(result.paused);assert.equal(f.agent.state().task.status,'waiting');assert.equal(f.agent.state().task.steps[0].status,'done');assert.equal(replayed,1);await f.agent.resume();assert.equal(replayed,1);assert.equal(f.agent.state().task.steps.filter(s=>s.status==='done').length,2);}finally{await f.close();}
});
test('manual takeover aborts in-flight tool, closes pending tool calls and resumes safely',async()=>{
 let entered,resolveEntered;const started=new Promise(r=>resolveEntered=r);let step=0;const sent=[];
 const f=await fixture({execute:async(_n,_a,signal)=>{resolveEntered();await new Promise((_r,reject)=>signal.addEventListener('abort',()=>reject(signal.reason),{once:true}));},fetch:async(_u,o)=>{const data=JSON.parse(o.body);sent.push(data);return ++step===1?response({tool_calls:[call('active','browser_wait',{ms:1000}),call('never','clear_traffic')]}):response({content:'Manual change checked.'});}});
 try{const pending=f.agent.chat({text:'Work until I take over.'});await started;f.agent.pause('handoff');assert((await pending).paused);assert.equal(f.agent.state().task.status,'waiting');await f.agent.resume();validHistory(sent.at(-1).messages);assert(JSON.parse(sent.at(-1).messages.find(m=>m.tool_call_id==='active').content).interrupted);assert(JSON.parse(sent.at(-1).messages.find(m=>m.tool_call_id==='never').content).skipped);}finally{await f.close();}
});
test('unchanged observations ignore fresh refs and repeated errors pause the task',()=>{
 const task=new Task('Inspect');for(let i=0;i<3;i++)assert.equal(task.detect('browser_read',{}, {url:'https://example.com',elements:[{ref:String(i),label:'Login'}]}),'');assert(task.detect('browser_read',{}, {url:'https://example.com',elements:[{ref:'new',label:'Login'}]}).includes('berulang'));
 const second=new Task('Inspect');assert.equal(second.detect('browser_click',{}, {error:'Missing element'}),'');assert.equal(second.detect('browser_click',{}, {error:'Missing element'}),'');assert(second.detect('browser_click',{}, {error:'Missing element'}).includes('tiga kali'));
});
test('plan limits are enforced and completed steps cannot be reset',()=>{assert.throws(()=>validateArgs('plan_task',{steps:[]}));assert.throws(()=>validateArgs('plan_task',{steps:['x'.repeat(201)]}));const t=new Task('x');t.plan(['Open','Verify']);t.update({stepId:'1',status:'done'});assert.throws(()=>t.update({stepId:'1',status:'running'}));assert.throws(()=>t.plan(['New']));});
