const test=require('node:test'),assert=require('node:assert/strict');
const http=require('node:http'),https=require('node:https'),tls=require('node:tls'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{fork}=require('node:child_process');
const forge=require('node-forge');
function certificate(){const keys=forge.pki.rsa.generateKeyPair(2048),c=forge.pki.createCertificate();c.publicKey=keys.publicKey;c.serialNumber='01';c.validity.notBefore=new Date(Date.now()-60000);c.validity.notAfter=new Date(Date.now()+86400000);const attrs=[{name:'commonName',value:'localhost'}];c.setSubject(attrs);c.setIssuer(attrs);c.setExtensions([{name:'basicConstraints',cA:true},{name:'keyUsage',keyCertSign:true,digitalSignature:true,keyEncipherment:true},{name:'subjectAltName',altNames:[{type:2,value:'localhost'},{type:7,ip:'127.0.0.1'}]}]);c.sign(keys.privateKey,forge.md.sha256.create());return {key:forge.pki.privateKeyToPem(keys.privateKey),cert:forge.pki.certificateToPem(c)};}
function listen(s){return new Promise(resolve=>s.listen(0,'127.0.0.1',()=>resolve(s.address().port)));}
function waitFor(child,predicate){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{child.removeListener('message',on);reject(new Error('Engine event timeout'));},15000);const on=msg=>{if(predicate(msg)){clearTimeout(timer);child.removeListener('message',on);resolve(msg);}};child.on('message',on);});}
function proxyGet(port,url){return new Promise((resolve,reject)=>{const req=http.get({hostname:'127.0.0.1',port,path:url,headers:{host:new URL(url).host}},res=>{let body='';res.on('data',b=>body+=b);res.on('end',()=>resolve({status:res.statusCode,body}));});req.on('error',reject);});}
function proxyTls(port,target,ca){return new Promise((resolve,reject)=>{const req=http.request({hostname:'127.0.0.1',port,method:'CONNECT',path:`127.0.0.1:${target}`});req.on('error',reject);req.on('connect',(_res,socket)=>{const secure=tls.connect({socket,servername:'localhost',ca},()=>secure.write(`GET /secure HTTP/1.1\r\nHost: localhost:${target}\r\nConnection: close\r\n\r\n`));let data='';secure.on('data',b=>data+=b);secure.on('end',()=>resolve(data));secure.on('error',reject);});req.end();});}
test('Whistle captures HTTP and HTTPS, trusts upstream certs and rejects invalid TLS', {timeout:60000},async t=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'arus-test-')),keys=certificate(),caPath=path.join(directory,'upstream.crt');fs.writeFileSync(caPath,keys.cert);
 const seen=[];const handler=(req,res)=>{let body='';req.on('data',b=>body+=b);req.on('end',()=>{seen.push({method:req.method,path:req.url,body,headers:req.headers});res.setHeader('Content-Type','application/json');res.end(req.url==='/large'?'x'.repeat(1024):JSON.stringify({ok:true,path:req.url}));});};
 const upstream=http.createServer(handler),secure=https.createServer(keys,handler),untrusted=https.createServer(certificate(),handler);
 const port=await listen(upstream),tlsPort=await listen(secure),badPort=await listen(untrusted);
 const child=fork(path.join(__dirname,'../src/engine.cjs'),[],{stdio:['ignore','pipe','pipe','ipc'],env:{...process.env,NODE_EXTRA_CA_CERTS:caPath}});let stderr='';child.stderr.on('data',b=>stderr+=b);
 t.after(()=>{child.kill();upstream.close();secure.close();untrusted.close();fs.rmSync(directory,{recursive:true,force:true});});
 const ready=waitFor(child,m=>m.kind==='ready');child.send({kind:'start',directory});const engine=await ready;
 const capture=waitFor(child,m=>m.kind==='rows' && m.rows.some(r=>r.url.endsWith('/hello') && r.status===200 && r.responseBody.includes('"ok":true')));
 const response=await proxyGet(engine.port,`http://127.0.0.1:${port}/hello`);assert.equal(response.status,200);await capture;
 const httpsCapture=waitFor(child,m=>m.kind==='rows' && m.rows.some(r=>r.url.includes('/secure') && r.status===200 && r.responseBody.includes('"ok":true')));
 const raw=await proxyTls(engine.port,tlsPort,engine.certificate);assert(raw.includes('200 OK'));assert(raw.includes('"ok":true'));const secureRows=await httpsCapture;const certRow=secureRows.rows.find(r=>r.url.includes('/secure'));assert(certRow.certificate?.issuer.includes('localhost'));assert(certRow.certificate?.tls.startsWith('TLS'));assert(certRow.timings.wait>=0);
 const bad=await proxyTls(engine.port,badPort,engine.certificate);assert(!bad.includes('"ok":true'),'untrusted upstream must not pass through');
 child.send({kind:'clear',epoch:5});
 const next=waitFor(child,m=>m.kind==='rows' && m.epoch===5 && m.rows.some(r=>r.url.endsWith('/after-clear')));await proxyGet(engine.port,`http://127.0.0.1:${port}/after-clear`);await next;

 async function settings(value){const reply=waitFor(child,m=>m.kind==='reply'&&m.id==='test-settings');child.send({kind:'settings',id:'test-settings',settings:value});const result=await reply;assert(!result.error,result.error);}
 const rule=(kind,extra={})=>({id:kind,kind,host:'127.0.0.1',path:'/',method:'*',enabled:true,...extra});
 await settings({sslBypass:[],rules:[rule('block')]});assert.equal((await proxyGet(engine.port,`http://127.0.0.1:${port}/blocked`)).status,403);
 const mapped=path.join(directory,'mapped.json');fs.writeFileSync(mapped,'{"mapped":true}');await settings({sslBypass:[],rules:[rule('map',{file:mapped,mime:'application/json',status:201})]});const mapResult=await proxyGet(engine.port,`http://127.0.0.1:${port}/mapped`);assert.equal(mapResult.status,201);assert.equal(mapResult.body,'{"mapped":true}');
 await settings({sslBypass:[],rules:[rule('throttle',{delay:250,kbps:0})]});const slow=Date.now();await proxyGet(engine.port,`http://127.0.0.1:${port}/slow`);assert(Date.now()-slow>=240);
 await settings({sslBypass:[],rules:[rule('throttle',{delay:0,kbps:8})]});const rateStart=Date.now();await proxyGet(engine.port,`http://127.0.0.1:${port}/large`);assert(Date.now()-rateStart>=850,'download throttle must delay response bytes');
 await settings({sslBypass:[],rules:[rule('breakpoint')]});const held=waitFor(child,m=>m.kind==='breakpoint');const interrupted=proxyGet(engine.port,`http://127.0.0.1:${port}/held`);const breakpoint=await held;assert(!seen.some(r=>r.path==='/held'),'held request must not reach upstream');const resolution=waitFor(child,m=>m.kind==='reply'&&m.id==='resolve');child.send({kind:'breakpoint-resolve',id:'resolve',breakpointId:breakpoint.data.id,decision:{action:'continue',method:'POST',headers:{'content-type':'application/json'},body:'{"edited":true}'}});assert.equal((await resolution).data,true);assert.equal((await interrupted).status,200);const edited=seen.find(r=>r.path==='/held');assert.equal(edited.method,'POST');assert.equal(edited.body,'{"edited":true}');
 const heldAbort=waitFor(child,m=>m.kind==='breakpoint');const cancelled=proxyGet(engine.port,`http://127.0.0.1:${port}/cancelled`);const abortData=await heldAbort;child.send({kind:'breakpoint-resolve',breakpointId:abortData.data.id,decision:{action:'abort'}});assert.equal((await cancelled).status,499);assert(!seen.some(r=>r.path==='/cancelled'));
 const postHeld=waitFor(child,m=>m.kind==='breakpoint');const postResponse=new Promise((resolve,reject)=>{const request=http.request({hostname:'127.0.0.1',port:engine.port,path:`http://127.0.0.1:${port}/post-held`,method:'POST',headers:{host:`127.0.0.1:${port}`,'content-type':'application/x-www-form-urlencoded'}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});request.on('error',reject);request.end('a=original');});const postData=await postHeld;assert.equal(postData.data.body,'a=original');child.send({kind:'breakpoint-resolve',breakpointId:postData.data.id,decision:{action:'continue',method:'POST',headers:postData.data.headers,body:'a=edited'}});assert.equal(await postResponse,200);assert.equal(seen.find(r=>r.path==='/post-held').body,'a=edited');
 await settings({sslBypass:['127.0.0.1'],rules:[]});const bypass=await proxyTls(engine.port,tlsPort,keys.cert);assert(bypass.includes('200 OK'),'SSL bypass uses the actual upstream certificate');
 await settings({sslBypass:[],rules:[]});
 const crypto=require('node:crypto');upstream.on('upgrade',(request,socket)=>{const accept=crypto.createHash('sha1').update(request.headers['sec-websocket-key']+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64');socket.write(`HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: ${accept}\r\n\r\n`);const body=Buffer.from('Arus websocket');socket.write(Buffer.concat([Buffer.from([0x81,body.length]),body]));socket.on('error',()=>{});});
 const frame=waitFor(child,m=>m.kind==='frame'&&m.data.text==='Arus websocket');const wsRequest=http.request({hostname:'127.0.0.1',port:engine.port,path:`ws://127.0.0.1:${port}/socket`,headers:{host:`127.0.0.1:${port}`,upgrade:'websocket',connection:'Upgrade','sec-websocket-key':crypto.randomBytes(16).toString('base64'),'sec-websocket-version':'13'}});let wsSocket;wsRequest.on('upgrade',(_response,socket)=>{wsSocket=socket;socket.on('error',()=>{});socket.resume();});wsRequest.end();await frame;wsSocket?.destroy();
 assert(!stderr.includes('uncaught'),stderr);
});
