(()=>{
'use strict';
let current=null,pinned=null,comparison=null,loading=false;
const labels={summary:'Ringkasan',requestHeaders:'Request headers',responseHeaders:'Response headers',requestBody:'Request body',responseBody:'Response body'},kinds={changed:'Berubah',added:'Ditambah',removed:'Dihapus',same:'Sama'};
const q=s=>document.querySelector(s),esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function controls(){q('#compare-pin').hidden=!pinned;q('#compare-pin-label').textContent=pinned?`A · ${pinned.method} ${pinned.url} · pilih request B`:'';q('#compare-button').disabled=loading||!current||current.id===pinned?.id;q('#compare-button span').textContent=pinned?'Bandingkan dengan A':'Pakai sebagai A';}
function render(){if(!comparison)return;for(const side of ['left','right']){const r=comparison[side];q('#compare-'+side).textContent=`${r.method} · ${r.status??'Menunggu'} · ${r.url}`;}
 q('#compare-sections').innerHTML=Object.entries(comparison.sections).map(([key,data])=>{const list=[...data.rows,...(q('#compare-same').checked?data.same:[])];return `<section class="compare-section"><h3>${labels[key]} <span>${data.changed} field berbeda</span></h3>${data.rawChanged&&data.changed===0?'<p class="body-note">Format mentah berbeda; field yang dibandingkan memiliki nilai sama.</p>':''}${data.truncated?'<p class="body-note">Tampilan dibatasi. Body besar atau nilai panjang dapat terpotong; periksa Raw untuk detail lengkap.</p>':''}${data.captureLimited?'<p class="body-note">Body yang tersedia memiliki batas capture. Perbandingan berlaku untuk data yang tertangkap.</p>':''}${list.length?`<div class="compare-table-scroll"><table class="compare-table"><thead><tr><th>Field</th><th>Request A</th><th>Request B</th></tr></thead><tbody>${list.map(r=>`<tr class="diff-${r.kind}"><th><span class="diff-kind">${kinds[r.kind]}</span>${esc(r.field)}</th><td><pre>${esc(r.left)}</pre></td><td><pre>${esc(r.right)}</pre></td></tr>`).join('')}</tbody></table></div>`:'<p class="compare-equal">Tidak ada perbedaan field yang terlihat.</p>'}</section>`;}).join('');
}
async function open(left,right){loading=true;controls();q('#compare-swap').disabled=true;try{comparison=await window.arus.compare(left,right);render();if(!q('#compare-dialog').open)q('#compare-dialog').showModal();}catch(e){q('#toast').textContent=e.message;q('#toast').hidden=false;setTimeout(()=>q('#toast').hidden=true,5000);}finally{loading=false;controls();q('#compare-swap').disabled=false;}}
q('#compare-button').addEventListener('click',()=>{if(!current)return;if(!pinned){pinned={...current};controls();}else open(pinned.id,current.id);});q('#compare-unpin').addEventListener('click',()=>{pinned=null;controls();});q('#compare-same').addEventListener('change',render);q('#compare-swap').addEventListener('click',()=>{if(comparison)open(comparison.right.id,comparison.left.id);});
document.addEventListener('arus-request-selected',e=>{current=e.detail;controls();});document.addEventListener('arus-traffic-clear',()=>{pinned=null;current=null;comparison=null;if(q('#compare-dialog').open)q('#compare-dialog').close();controls();});
})();
