'use strict';
(()=>{
 const q=s=>document.querySelector(s),api=window.arus,E=escape;
 const columns=[['method','METHOD',70],['request','REQUEST',240],['status','STATUS',70],['duration','TIME',75],['size','SIZE',70],['type','TYPE',95],['startedAt','STARTED',100],['ssl','SSL',100],['waterfall','WATERFALL',160]];
 let order=columns.map(c=>c[0]),shown=order.slice(0,5),widths={},settings={sslBypass:[],rules:[]},held=new Map(),heldId=null,mapFile=null,contentIds=null,searchSerial=0,contentQuery='';
 try{const saved=JSON.parse(localStorage.getItem('arus-log-columns'));if(saved){order=[...new Set([...saved.order.filter(k=>columns.some(c=>c[0]===k)),...order])];shown=saved.shown.filter(k=>order.includes(k));widths=saved.widths||{};}}catch{}
 const saveColumns=()=>{try{localStorage.setItem('arus-log-columns',JSON.stringify({order,shown,widths}));}catch{}};
 const selectedColumns=()=>order.filter(k=>shown.includes(k));
 const title=k=>columns.find(c=>c[0]===k)[1];
 function grid(){const c=selectedColumns();return c.map(k=>k==='request'?`minmax(${Math.max(100,Math.min(600,widths[k]||160))}px,1fr)`:`${Math.max(55,Math.min(600,widths[k]||columns.find(c=>c[0]===k)[2]))}px`).join(' ');}
 function header(){const el=q('.table-head');el.style.gridTemplateColumns=grid();el.innerHTML=selectedColumns().map(k=>`<span data-log-column="${k}"><button data-log-sort="${k}">${title(k)}</button><i role="separator" tabindex="0" aria-label="Lebar ${title(k)}" data-column-resize="${k}"></i></span>`).join('');}
 function bars(r){const t=r.timings||{},phases=['dns','connect','send','wait','receive'],total=phases.reduce((n,k)=>n+(t[k]||0),0);if(!total)return '<span class="subtle">—</span>';return `<span class="waterfall" title="${E(phases.map(k=>`${k}: ${t[k]==null?'—':time(t[k])}`).join(' · '))}">${phases.filter(k=>t[k]>0).map(k=>`<i class="phase-${k}" data-width="${Math.max(1,t[k]/total*100)}"></i>`).join('')}</span>`;}
 function row(r,yes){const u=parts(r),cells={method:`<span class="method ${E(r.method)}">${E(r.method)}</span>`,request:`<span class="request-cell"><span class="request-path">${r.bookmark?'★ ':''}${E(u.pathname+u.search)}</span><span class="request-host">${E(u.hostname)} · ${E(r.type)}${r.archived?' · Arsip':''}${r.proxyAction?' · '+E(r.proxyAction):''}</span></span>`,status:`<span class="status ${statusClass(r)}">${statusText(r)}</span>`,duration:`<span class="cell-meta">${time(r.duration)}</span>`,size:`<span class="cell-meta">${size(r.size)}</span>`,type:`<span class="cell-meta">${E(r.type)}</span>`,startedAt:`<span class="cell-meta">${E(new Date(r.startedAt).toLocaleTimeString('id-ID'))}</span>`,ssl:`<span class="cell-meta ssl-${E(r.sslState||'none')}">${({inspected:'Dibaca',bypassed:'Tunnel',failed:'Gagal',none:'HTTP'})[r.sslState]||'—'}</span>`,waterfall:bars(r)};return `<button role="option" aria-selected="${yes}" class="traffic-row ${yes?'selected':''}" data-id="${E(r.id)}" title="${E(r.url)}">${selectedColumns().map(k=>cells[k]).join('')}</button>`;}
 function filter(list){const method=q('#log-method').value,status=q('#log-status').value,type=q('#log-type').value,key=q('#log-sort').value,desc=q('#log-desc').checked;return list.filter(r=>(!method||r.method===method)&&(!type||r.type===type)&&(!status||(status==='error'?r.error:Math.floor(r.status/100)===Number(status)))&&(!q('#log-bookmarks').checked||r.bookmark)&&(!contentIds||contentIds.has(r.id))).sort((a,b)=>{let x=key==='startedAt'||key==='url'?String(a[key]||'').localeCompare(String(b[key]||'')):(a[key]||0)-(b[key]||0);return desc?-x:x;});}
 function cookies(headers,response){const value=Object.entries(headers||{}).find(([k])=>k.toLowerCase()===(response?'set-cookie':'cookie'))?.[1];if(!value)return '<p class="body-note">Tidak ada cookie.</p>';const lines=response?(Array.isArray(value)?value:String(value).split(/,(?=\s*[^;,=\s]+=)/)):String(value).split(';');return `<table class="headers-table">${lines.map(v=>{const i=v.indexOf('=');return `<tr><td>${E(i<0?v:v.slice(0,i).trim())}</td><td>${E(i<0?'':v.slice(i+1))}</td></tr>`;}).join('')}</table>`;}
 function detailView(tab,r){
  if(tab==='query'){const entries=[...new URL(r.url).searchParams];return entries.length?`<h3 class="headers-title">QUERY PARAMETERS</h3><table class="headers-table">${entries.map(([k,v])=>`<tr><td>${E(k)}</td><td>${E(v)}</td></tr>`).join('')}</table>`:'<p class="body-note">URL tidak memiliki query parameter.</p>';}
  if(tab==='cookies')return '<h3 class="headers-title">REQUEST COOKIES</h3>'+cookies(r.requestHeaders,false)+'<h3 class="headers-title">RESPONSE COOKIES</h3>'+cookies(r.responseHeaders,true);
  if(tab==='tls'){const cert=r.certificate;let html=`<div class="body-note">${E(({inspected:'HTTPS dibuka melalui CA Arus.',bypassed:'HTTPS diteruskan tanpa membuka isinya.',failed:'Koneksi HTTPS gagal.',none:'Request ini memakai HTTP.'})[r.sslState]||'Informasi SSL tidak tersedia.')}</div>`;if(!cert)return html+'<p class="fine-print">Detail sertifikat tersedia jika socket upstream memberikan informasi TLS. Tunnel, cache, koneksi yang dipakai ulang, dan Map Local bisa tidak menyediakannya.</p>';return html+Object.entries({TLS:cert.tls,Cipher:cert.cipher,Subject:cert.subject,Issuer:cert.issuer,'Berlaku mulai':cert.validFrom,'Berlaku sampai':cert.validTo,'SAN':cert.subjectAltName,'Serial':cert.serialNumber,'SHA-256':cert.fingerprint256,Sumber:cert.source}).map(([k,v])=>`<div class="info-line"><span>${E(k)}</span><strong>${E(v||'—')}</strong></div>`).join('');}
  if(tab==='websocket'){if(r.type!=='WebSocket')return '<p class="body-note">Pilih koneksi WebSocket untuk melihat pesan.</p>';const frames=r.frames||[];return `<div class="body-note">${frames.length} pesan terbaru · maksimal 200 per koneksi · 64 KiB per pesan.</div>`+frames.map(f=>`<article class="ws-frame"><header><strong>${f.isClient?'↑ Client → server':'↓ Server → client'}</strong><span>${E(f.id)} · opcode ${f.opcode} · ${size(f.length)}</span></header><pre>${E(f.closed?'Koneksi ditutup':f.error||f.text||(f.base64?'Binary (base64)\n'+f.base64:'Control frame'))}</pre>${f.truncated?'<small>Pesan dipotong.</small>':''}</article>`).join('');}
  if(tab==='notes')return `<label class="checkbox-line"><input id="request-bookmark" type="checkbox" ${r.bookmark?'checked':''}> Bookmark request ini</label><label class="field-label">Catatan</label><textarea id="request-note" maxlength="4000" rows="8" placeholder="Hal penting dari request ini…">${E(r.note||'')}</textarea><button id="request-note-save" class="primary">Simpan catatan</button><p class="fine-print">Bookmark dan catatan ikut tersimpan dalam sesi .arus.</p>`;
 }
 function after(){const minimum=selectedColumns().reduce((n,k)=>n+(k==='request'?widths[k]||160:widths[k]||columns.find(c=>c[0]===k)[2]),0)+32+Math.max(0,selectedColumns().length-1)*6;q('#traffic-rows').style.minWidth=minimum+'px';document.querySelectorAll('.table-head,.traffic-row').forEach(el=>{el.style.gridTemplateColumns=grid();el.style.minWidth=minimum+'px';});document.querySelectorAll('.waterfall [data-width]').forEach(el=>el.style.width=el.dataset.width+'%');}
 function detailReady(r){after();q('#request-note-save')?.addEventListener('click',async()=>{if(await act(()=>api.annotate(r.id,{bookmark:q('#request-bookmark').checked,note:q('#request-note').value})))toast('Catatan disimpan.');});}
 function timing(r){const phases=[['dns','DNS'],['connect','Koneksi / TLS'],['send','Kirim request'],['wait','Menunggu response'],['receive','Download']];return `<h3 class="headers-title">TIMING</h3>${bars(r)}${phases.map(([k,label])=>`<div class="info-line"><span><i class="phase-key phase-${k}"></i>${label}</span><strong>${time(r.timings?.[k])}</strong></div>`).join('')}<p class="fine-print">Waktu diukur oleh proxy. Fase yang tidak tersedia ditampilkan —; koneksi yang dipakai ulang bisa tidak memiliki fase koneksi baru.</p>`;}
 window.ArusNetwork={head:header,row,filter,detail:detailView,detailReady,timing,after};
 q('#traffic-scroll').prepend(q('.table-head'));
 function columnsUI(){q('#log-columns').innerHTML=order.map((k,i)=>`<div class="column-option"><label><input type="checkbox" data-show-column="${k}" ${shown.includes(k)?'checked':''} ${k==='request'?'disabled':''}> ${title(k)}</label><button data-move-column="${k}" data-direction="-1" ${i===0?'disabled':''} aria-label="Naikkan ${title(k)}">↑</button><button data-move-column="${k}" data-direction="1" ${i===order.length-1?'disabled':''} aria-label="Turunkan ${title(k)}">↓</button></div>`).join('');}
 q('#log-options-button').onclick=()=>{columnsUI();q('#network-options-dialog').showModal();};
 for(const id of ['method','status','type','sort','desc','bookmarks'])q('#log-'+id).onchange=()=>{follow=false;render();};
 q('#log-columns').onchange=e=>{const k=e.target.dataset.showColumn;if(!k)return;shown=e.target.checked?[...shown,k]:shown.filter(x=>x!==k);saveColumns();render();};
 q('#log-columns').onclick=e=>{const b=e.target.closest('[data-move-column]');if(!b)return;const i=order.indexOf(b.dataset.moveColumn),j=i+Number(b.dataset.direction);if(j<0||j>=order.length)return;[order[i],order[j]]=[order[j],order[i]];saveColumns();columnsUI();render();};
 q('.table-head').onclick=e=>{const b=e.target.closest('[data-log-sort]');if(!b)return;const key=b.dataset.logSort;if(['method','request','type','ssl','waterfall'].includes(key))return;if(q('#log-sort').value===key)q('#log-desc').checked=!q('#log-desc').checked;else q('#log-sort').value=key;follow=false;render();};
 q('.table-head').onpointerdown=e=>{const handle=e.target.closest('[data-column-resize]');if(!handle)return;e.preventDefault();const start=e.clientX,k=handle.dataset.columnResize,width=handle.parentElement.getBoundingClientRect().width;const move=ev=>{widths[k]=Math.max(55,Math.min(600,width+ev.clientX-start));document.querySelectorAll('.table-head,.traffic-row').forEach(el=>el.style.gridTemplateColumns=grid());};const end=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',end);saveColumns();};document.addEventListener('pointermove',move);document.addEventListener('pointerup',end,{once:true});};
 q('.table-head').onkeydown=e=>{const k=e.target.dataset.columnResize;if(!k||!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();widths[k]=Math.max(55,Math.min(600,(widths[k]||columns.find(c=>c[0]===k)[2])+(e.key==='ArrowLeft'?-10:10)));saveColumns();render();};
 async function search(){const serial=++searchSerial,value=q('#content-search').value;contentQuery=value;q('#content-search-result').textContent='Mencari…';const ids=await act(()=>api.searchContent(value));if(serial!==searchSerial)return;if(ids){contentIds=value?new Set(ids):null;q('#content-search-result').textContent=value?`${ids.length} request cocok. Jalankan lagi untuk memasukkan traffic baru.`:'Pencarian isi dinonaktifkan.';follow=false;render();}}
 q('#content-search-run').onclick=search;q('#content-search').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();search();}};q('#content-search-clear').onclick=()=>{searchSerial++;contentIds=null;contentQuery='';q('#content-search').value='';q('#content-search-result').textContent='Pencarian isi dinonaktifkan.';render();};
 q('#log-reset').onclick=()=>{for(const k of ['method','status','type'])q('#log-'+k).value='';q('#log-sort').value='startedAt';q('#log-desc').checked=false;q('#log-bookmarks').checked=false;order=columns.map(c=>c[0]);shown=order.slice(0,5);widths={};saveColumns();q('#content-search-clear').click();columnsUI();};
 q('#sessions-button').onclick=()=>q('#sessions-dialog').showModal();q('#session-save').onclick=async()=>{if(await act(()=>api.sessionSave()))toast('Sesi lengkap disimpan.');};q('#session-open').onclick=async()=>{const result=await act(()=>api.sessionOpen());if(result){q('#sessions-dialog').close();toast(`${result.count} request diimport.`);}};q('#session-har').onclick=()=>{q('#sessions-dialog').close();q('#export-button').click();};
 function proxyUI(){q('#proxy-active-count').textContent=settings.rules.filter(r=>r.enabled).length||'';q('#ssl-domains').innerHTML=settings.sslBypass.map((h,i)=>`<div class="proxy-rule"><strong>${E(h)}</strong><span>Tunnel</span><button data-remove-ssl="${i}">Baca HTTPS</button></div>`).join('')||'<p class="fine-print">Semua domain HTTPS dibaca.</p>';q('#rules-count').textContent=settings.rules.length;const names={block:'Block',map:'Map Local',breakpoint:'Breakpoint',throttle:'Koneksi lambat'};q('#proxy-rules').innerHTML=settings.rules.map((r,i)=>`<div class="proxy-rule"><label><input type="checkbox" data-toggle-rule="${i}" ${r.enabled?'checked':''}> <strong>${names[r.kind]}</strong></label><div><span>${E(r.method)} ${E(r.host+r.path)}</span><small>${E(r.kind==='map'?r.file:r.kind==='throttle'?`${r.delay} ms · ${r.kbps||'∞'} kbps`:'')}</small></div><button data-remove-rule="${i}" aria-label="Hapus aturan">×</button></div>`).join('')||'<p class="body-note">Belum ada aturan. Tambahkan aturan pertama di bawah.</p>';}
 async function saveProxy(next){const value=await act(()=>api.proxySave(next));if(value){settings=value;proxyUI();toast('Pengaturan proxy diterapkan.');return true;}return false;}
 q('#proxy-button').onclick=()=>{proxyUI();q('#proxy-dialog').showModal();};q('#ssl-add').onclick=async()=>{const host=q('#ssl-domain').value.trim();if(!host)return;if(await saveProxy({...settings,sslBypass:[...new Set([...settings.sslBypass,host])]}))q('#ssl-domain').value='';};q('#ssl-export-ca').onclick=()=>act(()=>api.certificate());q('#ssl-domains').onclick=e=>{const b=e.target.closest('[data-remove-ssl]');if(b)saveProxy({...settings,sslBypass:settings.sslBypass.filter((_,i)=>i!==Number(b.dataset.removeSsl))});};
 q('#proxy-rules').onchange=e=>{if(!e.target.dataset.toggleRule)return;const i=Number(e.target.dataset.toggleRule);saveProxy({...settings,rules:settings.rules.map((r,j)=>j===i?{...r,enabled:e.target.checked}:r)});};q('#proxy-rules').onclick=e=>{const b=e.target.closest('[data-remove-rule]');if(b)saveProxy({...settings,rules:settings.rules.filter((_,i)=>i!==Number(b.dataset.removeRule))});};
 q('#rule-kind').onchange=()=>{q('#rule-map-fields').hidden=q('#rule-kind').value!=='map';q('#rule-throttle-fields').hidden=q('#rule-kind').value!=='throttle';};q('#rule-file-pick').onclick=async()=>{const file=await act(()=>api.mapFile());if(file){mapFile=file;q('#rule-file-name').textContent=file.split(/[\\/]/).pop();}};
 q('#proxy-rule-form').onsubmit=async e=>{e.preventDefault();const rule={kind:q('#rule-kind').value,host:q('#rule-host').value.trim(),path:q('#rule-path').value,method:q('#rule-method').value,enabled:true};if(rule.kind==='map')Object.assign(rule,{file:mapFile,mime:q('#rule-mime').value,status:Number(q('#rule-status').value)});if(rule.kind==='throttle')Object.assign(rule,{delay:Number(q('#rule-delay').value),kbps:Number(q('#rule-kbps').value)});await saveProxy({...settings,rules:[...settings.rules,rule]});};
 function breakpointUI(){q('#breakpoint-queue').hidden=!held.size;q('#breakpoint-queue').textContent=`${held.size} request ditahan · Periksa`;if(!held.size){heldId=null;if(q('#breakpoint-dialog').open)q('#breakpoint-dialog').close();return;}if(!held.has(heldId))heldId=held.keys().next().value;q('#breakpoint-list').innerHTML=[...held.values()].map(r=>`<button data-held-id="${E(r.id)}" class="${r.id===heldId?'selected':''}">${E(r.method)} ${E(new URL(r.url).pathname)}</button>`).join('');}
 function showHeld(){breakpointUI();const r=held.get(heldId);if(!r)return;q('#breakpoint-url').textContent=r.url;q('#breakpoint-method').value=r.method;q('#breakpoint-headers').value=JSON.stringify(r.headers,null,2);q('#breakpoint-body').value=r.body;q('#breakpoint-body').disabled=!r.editable;q('#breakpoint-note').textContent=r.editable?'Request belum dikirim. Periksa perubahan lalu teruskan atau batalkan.':`Body biner / terkompresi (${size(r.size)}): diteruskan asli; body tidak dapat diedit.`;if(!q('#breakpoint-dialog').open)q('#breakpoint-dialog').showModal();}
 q('#breakpoint-queue').onclick=showHeld;q('#breakpoint-list').onclick=e=>{const b=e.target.closest('[data-held-id]');if(b){heldId=b.dataset.heldId;showHeld();}};
 q('#breakpoint-abort').onclick=()=>act(()=>api.breakpointResolve(heldId,{action:'abort'}));q('#breakpoint-form').onsubmit=async e=>{e.preventDefault();const id=heldId;try{await api.breakpointResolve(id,{action:'continue',method:q('#breakpoint-method').value,headers:JSON.parse(q('#breakpoint-headers').value),body:q('#breakpoint-body').value});}catch(e){toast(e.message);}};
 q('#traffic-rows').oncontextmenu=async e=>{const b=e.target.closest('[data-id]');if(!b)return;e.preventDefault();await select(b.dataset.id);q('#request-menu-title').textContent=detail?.url||'';q('#request-menu-dialog').showModal();};q('#request-menu-dialog').onclick=e=>{const b=e.target.closest('[data-request-action]');if(!b)return;q('#request-menu-dialog').close();const action=b.dataset.requestAction;if(['url','curl'].includes(action))copy(action);else if(action==='replay')q('#replay-button').click();else if(action==='compare')q('#compare-button').click();else if(action==='bookmark')q('[data-tab="notes"]').click();else if(action==='rule'){q('#rule-host').value=parts(detail).hostname;q('#rule-path').value=parts(detail).pathname;q('#proxy-button').click();}};
 document.querySelectorAll('#network-options-dialog .dialog-close,#sessions-dialog .dialog-close,#proxy-dialog .dialog-close,#breakpoint-dialog .dialog-close,#request-menu-dialog .dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
 document.addEventListener('arus-traffic-clear',()=>{contentIds=null;contentQuery='';searchSerial++;q('#content-search').value='';});
 api.onEvent(event=>{if(event.kind==='proxy-settings'){settings=event.data;proxyUI();}if(event.kind==='breakpoint'){held.set(event.data.id,event.data);breakpointUI();toast('Request ditahan. Klik antrean breakpoint untuk memeriksa.');}if(event.kind==='breakpoint-done'){const previous=heldId;held.delete(event.id);breakpointUI();if(previous===event.id&&held.size&&q('#breakpoint-dialog').open)showHeld();}});
 act(async()=>{const state=await api.proxyState();settings=state.settings;held=new Map(state.pending.map(r=>[r.id,r]));proxyUI();breakpointUI();render();});
})();
