'use strict';
const {MAX_BODY}=require('./capture.cjs');
const MAX_FILE=64*1024*1024;
function headers(value){if(!value||typeof value!=='object'||Array.isArray(value))return {};return Object.fromEntries(Object.entries(value).slice(0,500).filter(([k,v])=>k.length<=500&&(typeof v==='string'||Array.isArray(v))).map(([k,v])=>[k,String(v).slice(0,64000)]));}
function text(v,max=MAX_BODY){return typeof v==='string'?v.slice(0,max):'';}
function number(v,max=1e12){return Number.isFinite(v)&&v>=0&&v<=max?v:null;}
function row(value){if(!value||typeof value.url!=='string'||value.url.length>8192)throw Error('URL sesi tidak valid.');const url=new URL(value.url);if(!['http:','https:','ws:','wss:'].includes(url.protocol)||url.username||url.password)throw Error('URL sesi tidak didukung.');const date=new Date(value.startedAt);if(!Number.isFinite(date.getTime()))throw Error('Tanggal request tidak valid.');return {url:url.href,method:text(value.method,20)||'GET',startedAt:date.toISOString(),status:number(value.status,599),statusText:text(value.statusText,200),duration:number(value.duration),size:number(value.size)||0,type:text(value.type,50)||'Imported',mime:text(value.mime,300),protocol:text(value.protocol,100),remoteAddress:text(value.remoteAddress,200),requestHeaders:headers(value.requestHeaders),responseHeaders:headers(value.responseHeaders),requestBody:text(value.requestBody),responseBody:text(value.responseBody),bodyNote:text(value.bodyNote,1000),error:text(value.error,2000),bookmark:value.bookmark===true,note:text(value.note,4000),archived:true,sslState:text(value.sslState,40),timings:Object.fromEntries(['dns','connect','send','wait','receive'].map(k=>[k,number(value.timings?.[k])])),certificate:value.certificate?Object.fromEntries(['subject','issuer','validFrom','validTo','serialNumber','fingerprint256','subjectAltName','tls','cipher','source'].map(k=>[k,text(value.certificate[k],4000)])):null,imageBase64:/^image\/(png|jpeg|gif|webp|avif|bmp)(;|$)/i.test(value.mime)&&typeof value.imageBase64==='string'&&value.imageBase64.length<=Math.ceil(MAX_BODY*4/3)&&/^[a-z0-9+/=]*$/i.test(value.imageBase64)?value.imageBase64:'',frames:Array.isArray(value.frames)?value.frames.slice(-200).map(f=>({id:text(f.id,100),isClient:f.isClient===true,opcode:number(f.opcode,15)||0,length:number(f.length)||0,text:text(f.text,65536),base64:text(f.base64,90000),truncated:f.truncated===true,closed:f.closed===true,error:text(f.error,1000)})):[]};}
function harHeaders(items){return Object.fromEntries((Array.isArray(items)?items:[]).slice(0,500).filter(h=>typeof h.name==='string'&&typeof h.value==='string').map(h=>[h.name,h.value]));}
function importSession(input){if(Buffer.byteLength(input)>MAX_FILE)throw Error('File sesi maksimal 64 MiB.');const data=JSON.parse(input);let rows;if(data.format==='arus-session'&&data.version===1)rows=data.rows;else if(data.log?.version==='1.2'&&Array.isArray(data.log.entries))rows=data.log.entries.map(e=>({url:e.request?.url,method:e.request?.method,startedAt:e.startedDateTime,status:e.response?.status,statusText:e.response?.statusText,duration:e.time,size:e.response?.content?.size,type:'Imported',mime:e.response?.content?.mimeType,protocol:e.response?.httpVersion,requestHeaders:harHeaders(e.request?.headers),responseHeaders:harHeaders(e.response?.headers),requestBody:e.request?.postData?.text,responseBody:e.response?.content?.encoding==='base64'?'':e.response?.content?.text,bodyNote:e.response?.content?.encoding==='base64'?'HAR berisi konten base64; tampilan teks dihilangkan.':e._arus?.bodyOmitted?'Body dihilangkan dari HAR sumber.':'',timings:e.timings}));else throw Error('Pilih sesi Arus atau HAR 1.2.');if(!Array.isArray(rows)||rows.length>3000)throw Error('Sesi maksimal 3.000 request.');const result=rows.map(row);if(Buffer.byteLength(JSON.stringify(result))>48*1024*1024)throw Error('Data sesi melebihi 48 MiB.');return result;}
function serializeSession(store){return JSON.stringify({format:'arus-session',version:1,createdAt:new Date().toISOString(),rows:[...store.rows.keys()].map(id=>store.get(id))});}
function searchRows(store,query){if(typeof query!=='string'||query.length>2000)throw Error('Pencarian maksimal 2.000 karakter.');const q=query.toLowerCase();return [...store.rows.values()].filter(r=>[r.url,r.method,String(r.status),r.note,JSON.stringify(r.requestHeaders),JSON.stringify(r.responseHeaders),r.requestBody,r.responseBody,...(r.frames||[]).map(f=>f.text)].some(v=>String(v||'').toLowerCase().includes(q))).map(r=>r.id);}
module.exports={importSession,serializeSession,searchRows,MAX_FILE};
